spring:
  application:
    name: realworld
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:real-world-main;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

jwt:
  token:
    secret: bXktcmVhbHdvcmxkLXNwcmluZy1hY2Nlc3MtdG9rZW4tbXktcmVhbHdvcmxkLXNwcmluZy1hY2Nlc3MtdG9rZW4tbXktcmVhbHdvcmxkLXNwcmluZy1hY2Nlc3MtdG9rZW4=
    access-time: 1800000  # 30minutes
